### ISSUE TITLE
Would be good to add `${USER}` to the `lxd` group

### ISSUE THREAD

**Issue by Saviq** [whywaita/setup-lxd#1]
To avoid `sudo` whenever calling `lxc`, would be good to add `${USER}` to the `lxd` group.

It will still require a `sg lxd -c …` though, as there doesn't seem to be a way to refresh groups within a workflow.

**Comment by whywaita** [comment]
@Saviq Thank you for your comment.

I already check `lxc launch` without sudo  in [test by GitHub Actions](https://github.com/whywaita/setup-lxd/blob/33fb9bd22fc20eae210ff1ff09cc26a0e5f2627f/.github/workflows/test.yaml#L29).

Can you provide your workflow?

**Comment by Saviq** [comment]
Hi @whywaita indeed, looks like enough is set up in the runners these days, I was unnecessarily using `sg lxd`.
